application: ip-custom
version: 1
runtime: go
api_version: go1

handlers:
- url: /.*
  script: _go_app
- url: /get
  script: _go_app
- url: /cron
  login: admin
  script: _go_app
- url: /update
  login: admin
  script: _go_app
